language: python
python:
 - "2.7"
 - "3.6"
 - "3.8"
install:
 - pip install -r requirements.txt
git:
  depth: 50
jobs:
  include:
  - name: "HW-1"
    python: "3.8"
#    env: 
#     - TEST_SUITE1=3
#     - TEST_SUITE2=4
script:
 - pytest
