language: python
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"
install:
 - pip install -r requirements.txt
git:
  depth: 50
jobs:
  include:
  - name: "Unit Test-1"
    python: "3.8"
    env: 
     - TEST_SUITE1=3
     - TEST_SUITE2=4
script: ./test/test_code.py $TEST_SUITE1 $TEST_SUITE2
